default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: order_monok_development

test:
  <<: *default
  database: order_monok_test

production:
  primary: &primary_production
    <<: *default
    database: order_monok_production
    username: order_monok
    password: <%= ENV["ORDER_MONOK_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: order_monok_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: order_monok_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: order_monok_production_cable
    migrations_paths: db/cable_migrate